import type { TranslationCatalog } from "@/lib/i18n/types";
import en from "@/lib/i18n/en";
import { te as legacy } from "@/lib/i18n/regional";
import { AI_I18N } from "@/lib/i18n/ai-i18n";

const overrides: TranslationCatalog = {
  ...legacy, ...AI_I18N.te,
  "app.name":"UNK AI","auth.welcomeTitle":"UNK AI కు స్వాగతం","auth.welcomeBody":"తర్వాత: సైన్ ఇన్ చేయండి లేదా ఖాతా తెరవండి. పరిచయాలు, దినచర్య, మందులు ఏర్పాటు చేయండి.","auth.welcomeSteps":"1. సైన్ ఇన్ చేయండి లేదా ఖాతా తెరవండి\n2. పరిచయాలు, దినచర్య, మందులు జోడించండి\n3. పూర్తయ్యాక హోమ్ తెరవండి","auth.loginSteps":"1. మీ ఇమెయిల్ ఇవ్వండి.\n2. మేము పంపిన భద్రతా ఇమెయిల్ తెరవండి.\n3. UNK AI తెరవడానికి “అవును, నేనే” నొక్కండి.",
  "auth.signup":"ఖాతా తెరవండి","auth.password":"పాస్‌వర్డ్","auth.confirmPassword":"పాస్‌వర్డ్ నిర్ధారించండి","auth.fullName":"పూర్తి పేరు","auth.forgotPassword":"పాస్‌వర్డ్ మర్చిపోయారా?","auth.createAccount":"ఖాతా తెరవండి","auth.continueGuest":"అతిథిగా కొనసాగండి","auth.loginSafetyHint":"మీ భద్రత కోసం, సైన్ ఇన్ చేస్తున్నది మీరేనని నిర్ధారించడానికి సురక్షిత లింక్‌ను ఇమెయిల్ చేస్తాము.","auth.emailLinkButton":"భద్రతా తనిఖీ పంపండి","auth.sendingEmailLink":"భద్రతా తనిఖీ పంపుతోంది…","auth.usePasswordInstead":"పాస్‌వర్డ్‌తో సైన్ ఇన్ చేయండి","auth.useEmailLinkInstead":"ఇమెయిల్ ఉపయోగించండి","auth.signupButton":"ఖాతా తెరవండి","auth.creatingAccount":"ఖాతా తయారవుతోంది…","auth.noAccount":"ఖాతా లేదా?","auth.hasAccount":"ఇప్పటికే ఖాతా ఉందా?","auth.resetTitle":"పాస్‌వర్డ్ మార్చండి","auth.resetEmailSent":"ఆ ఇమెయిల్ ఉంటే సూచనలు పంపాము.","auth.resetNewPassword":"కొత్త పాస్‌వర్డ్","auth.resetConfirm":"కొత్త పాస్‌వర్డ్ నిర్ధారించండి","auth.resetButton":"పాస్‌వర్డ్ నవీకరించండి",
  "auth.error.nameRequired":"పూర్తి పేరు ఇవ్వండి (కనీసం 2 అక్షరాలు).","auth.error.passwordShort":"పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి.","auth.error.passwordMismatch":"పాస్‌వర్డ్‌లు సరిపోలలేదు.","auth.error.emailInUse":"ఈ ఇమెయిల్ ఇప్పటికే నమోదైంది.","auth.error.invalidCredentials":"ఇమెయిల్ లేదా పాస్‌వర్డ్ తప్పు.","auth.error.sendFailed":"ఇమెయిల్ పంపలేకపోయాం. చిరునామా చూసి మళ్లీ ప్రయత్నించండి.","auth.error.resendTestMode":"ఇమెయిల్ సేవ ఇంకా పరీక్షలో ఉంది. డెవలపర్‌ను సంప్రదించండి లేదా పాస్‌వర్డ్‌తో సైన్ ఇన్ చేయండి.","auth.error.notConfigured":"సర్వర్‌లో లాగిన్ ఇమెయిల్ ఏర్పాటు కాలేదు. డెవలపర్‌ను సంప్రదించండి.","auth.error.dbUnavailable":"ఈ సర్వర్‌లో ఖాతా నిల్వ సిద్ధంగా లేదు. తర్వాత ప్రయత్నించండి.","auth.changeLanguage":"భాష మార్చండి","auth.setupCallsTitle":"మీ కాల్స్ ఏర్పాటు చేయండి","auth.setupCallsHint":"తరచూ కాల్ చేసే కుటుంబ సభ్యుల నంబర్లు జోడించండి. హోమ్‌లో ఆకుపచ్చ కాల్ బటన్ నొక్కండి.","auth.setupCallsYourPhone":"మీ ఫోన్ నంబర్ (ఐచ్ఛికం)","auth.setupCallsContinue":"UNK AI కు కొనసాగండి","home.doctor":"UNK డాక్టర్",
  "settings.restartSetup":"సెటప్ మళ్లీ ప్రారంభించండి","settings.restartLanguage":"భాష ఎంపిక నుంచి ప్రారంభించండి","settings.memoryTitle":"జ్ఞాపకం","settings.memoryHint":"ఇష్టమైన ఆహారం లేదా దినచర్య వంటి సురక్షిత ఇష్టాలను UNK గుర్తుంచుకోగలదు. వైద్య వివరాలు మెడికల్‌లోనే ఉంటాయి.","settings.memoryEnabled":"UNK గుర్తుంచుకోవడానికి అనుమతించండి","settings.memoryView":"దాచిన జ్ఞాపకాలు","settings.memoryEmpty":"ఇంకా జ్ఞాపకాలు లేవు.","settings.memoryClear":"అన్ని జ్ఞాపకాలు తొలగించండి","settings.memoryDelete":"తొలగించండి",
  "shopping.title":"షాపింగ్ సహాయం","shopping.intro":"UNK అడుగడుగునా చూపిస్తుంది. షాపింగ్ యాప్ లేదా వెబ్‌సైట్‌లో డబ్బు మీరే చెల్లించండి.","shopping.step1":"షాపింగ్ యాప్ లేదా వెబ్‌సైట్ తెరవండి (Blinkit, Amazon వంటివి).","shopping.step2":"పైన ఉన్న వెతుకు పట్టీని కనుగొనండి.","shopping.step3":"కావలసినది వెతకండి.","shopping.step4":"సరైన వస్తువు ఎంచుకోండి.","shopping.step5":"కార్ట్‌లో జోడించండి.","shopping.step6":"కార్ట్ తెరిచి ఆర్డర్ చూడండి.","shopping.step7":"చెల్లింపు దశకు వెళ్లండి.","shopping.step8":"సిద్ధమైనప్పుడు మీరే చెల్లించండి.","shopping.safety":"UNK మీ కోసం ఆర్డర్ చేయదు లేదా చెల్లింపు వివరాలు నమోదు చేయదు.","shopping.askUnk":"షాపింగ్‌లో UNK ను అడగండి",
  "medical.title":"మెడికల్","medical.intro":"మీ ఆరోగ్య సమాచారం ఇక్కడ ఉంటుంది. UNK సులభంగా వివరిస్తుంది, కానీ లైసెన్స్ పొందిన డాక్టర్ కాదు.","medical.symptoms":"లక్షణాల తనిఖీ, ఆరోగ్య సహాయం","medical.medicines":"మందుల గుర్తులు","medical.profile":"వైద్య వివరాలు","medical.findDoctor":"దగ్గరి డాక్టర్లను కనుగొనండి","medical.disclaimer":"అత్యవసరంలో అత్యవసర బటన్ నొక్కండి. తీవ్రమైన లక్షణాలకు డాక్టర్ లేదా ఆసుపత్రిని సంప్రదించండి.","medical.medicinesHint":"గుర్తులు జోడించండి. UNK మోతాదు మార్చదు లేదా మందు సూచించదు.","medical.medicineName":"మందు పేరు","medical.dose":"మోతాదు / సూచనలు","medical.time":"సమయం","medical.days":"రోజులు","medical.daily":"ప్రతిరోజూ","medical.addMedicine":"మందు గుర్తు జోడించండి","medical.profileHint":"ఈ పరికరంలో ఉంచడానికి మీకు సౌకర్యమైన సమాచారమే జోడించండి.","medical.conditions":"అనారోగ్యాలు","medical.allergies":"అలర్జీలు","medical.bloodGroup":"రక్త వర్గం (ఐచ్ఛికం)","medical.emergencyNotes":"అత్యవసర గమనికలు",
  "routine.title":"నా దినచర్య","routine.intro":"మీ క్యాలెండర్—గుర్తులు చూడటానికి రోజు నొక్కండి లేదా “25న డాక్టర్ దగ్గరకు వెళ్లాలని గుర్తు చేయి” అని UNK కు చెప్పండి.","routine.empty":"ఇంకా దినచర్య లేదు. “UNK, గుర్తు చేయి…” అని చెప్పండి లేదా కింద జోడించండి.","routine.task":"ఏమి గుర్తుంచుకోవాలి","routine.time":"సమయం","routine.days":"ఎంత తరచుగా","routine.daily":"ప్రతిరోజూ","routine.anytime":"ఎప్పుడైనా","routine.add":"గుర్తు జోడించండి","routine.remove":"తొలగించండి","routine.voice":"UNK కు చెప్పి జోడించండి","routine.today":"ఈ రోజు","routine.prevMonth":"మునుపటి నెల","routine.nextMonth":"తర్వాతి నెల","routine.dayEmpty":"ఈ రోజుకు ఏదీ లేదు. కింద గుర్తు జోడించండి.","routine.dayAgenda":"ఈ రోజు ప్రణాళికలు","routine.recurring":"రోజువారీ, పునరావృతం","routine.recurringEmpty":"ఇంకా రోజువారీ దినచర్య లేదు.",
  "routine.month.january":"జనవరి","routine.month.february":"ఫిబ్రవరి","routine.month.march":"మార్చి","routine.month.april":"ఏప్రిల్","routine.month.may":"మే","routine.month.june":"జూన్","routine.month.july":"జూలై","routine.month.august":"ఆగస్టు","routine.month.september":"సెప్టెంబర్","routine.month.october":"అక్టోబర్","routine.month.november":"నవంబర్","routine.month.december":"డిసెంబర్","routine.weekday.sun":"ఆది","routine.weekday.mon":"సోమ","routine.weekday.tue":"మంగళ","routine.weekday.wed":"బుధ","routine.weekday.thu":"గురు","routine.weekday.fri":"శుక్ర","routine.weekday.sat":"శని","routine.kind.appointment":"అపాయింట్‌మెంట్","routine.kind.reminder":"గుర్తు","routine.kind.task":"పని","routine.kind.medicine":"మందు",
  "emergency.title":"అత్యవసరం","emergency.intro":"కాల్ చేయడానికి ఒక్కసారి నొక్కండి. పొడవైన మెనూలు లేవు.","emergency.ambulance":"అంబులెన్స్ — 108","emergency.police":"పోలీసు — 100","emergency.fire":"అగ్నిమాపక — 101","emergency.universal":"సార్వత్రిక అత్యవసరం — 112","emergency.note":"ఈ నంబర్లు భారతదేశానికి చెందినవి. అత్యవసరంలో స్థానిక సేవకు కాల్ చేయండి.",
  "setup.step.contacts":"{total}లో దశ {step} — ఫోన్, పరిచయాలు","setup.step.routine":"{total}లో దశ {step} — రోజువారీ దినచర్య","setup.step.medicines":"{total}లో దశ {step} — మందులు","setup.step.complete":"{total}లో దశ {step} — పూర్తయింది","setup.contacts.title":"మీ ఫోన్, పరిచయాలు","setup.contacts.subtitle":"ముందు మీ నంబర్, తర్వాత తరచూ కాల్ చేసే కుటుంబ సభ్యులను జోడించండి. ఇప్పుడు దాటవేసి తర్వాత మార్చవచ్చు.","setup.contacts.yourPhone":"మీ ఫోన్ నంబర్","setup.contacts.voiceHint":"ఇలా చెప్పండి: “UNK, రాహుల్‌ను నా కొడుకుగా జోడించు. అతని నంబర్ 9876543210.”","setup.contacts.add":"పరిచయం జోడించండి","setup.contacts.skip":"ఇప్పుడు దాటవేయండి","setup.contacts.continue":"నా దినచర్యకు కొనసాగండి","setup.contacts.name":"పేరు","setup.contacts.relationship":"బంధం","setup.contacts.phone":"ఫోన్ నంబర్","setup.contacts.confirmTitle":"ఈ పరిచయాన్ని సేవ్ చేయాలా?","setup.contacts.confirmBody":"{name}ను మీ {relationship}గా జోడించండి. ఫోన్: {phone}","setup.contacts.confirmYes":"అవును, సేవ్ చేయండి","setup.contacts.confirmNo":"కాదు, మళ్లీ ప్రయత్నించండి","setup.contacts.voicePlaceholder":"పరిచయం జోడించడానికి మాట్లాడండి లేదా టైప్ చేయండి…","setup.contacts.listen":"మాట్లాడటానికి నొక్కండి","setup.contacts.stop":"ఆపండి","setup.contacts.send":"అర్థం చేసుకోండి",
  "setup.routine.title":"మీ దినచర్యను UNK కు చెప్పండి","setup.routine.subtitle":"సహజంగా చెప్పండి. ఉదాహరణ: “7కు లేస్తాను, 8కు అల్పాహారం, 9కు మందు, 6కు నడక, 10కు నిద్ర.”","setup.routine.voicePlaceholder":"మీ రోజువారీ దినచర్య చెప్పండి…","setup.routine.yourRoutine":"మీ దినచర్య","setup.routine.lookRight":"ఇది సరైనదేనా?","setup.routine.confirm":"అవును, సేవ్ చేయండి","setup.routine.skip":"ఇప్పుడు దాటవేయండి","setup.routine.edit":"మార్చండి","setup.routine.save":"కొనసాగండి","setup.routine.listen":"మాట్లాడటానికి నొక్కండి","setup.routine.stop":"ఆపండి","setup.routine.send":"దినచర్యను అర్థం చేసుకోండి","setup.routine.empty":"దినచర్య అర్థం కాలేదు. మళ్లీ ప్రయత్నించండి.",
  "setup.medicines.title":"మీ మందులు ఏర్పాటు చేయండి","setup.medicines.subtitle":"మందుల గుర్తులు జోడించండి. UNK మోతాదు మార్చదు లేదా మందు సూచించదు.","setup.medicines.add":"మందు జోడించండి","setup.medicines.skip":"ఇప్పుడు దాటవేయండి","setup.medicines.name":"మందు పేరు","setup.medicines.dose":"మోతాదు / సూచనలు","setup.medicines.time":"సమయం","setup.medicines.days":"రోజులు","setup.medicines.notes":"గమనికలు (ఐచ్ఛికం)","setup.medicines.confirmTitle":"ఈ గుర్తు సరైనదేనా?","setup.medicines.confirmBody":"ప్రతిరోజూ {time}కు {name} తీసుకోవాలని గుర్తు చేయాలా?","setup.medicines.confirmYes":"అవును, సేవ్ చేయండి","setup.medicines.confirmNo":"కాదు, మళ్లీ ప్రయత్నించండి","setup.medicines.voicePlaceholder":"ఉదాహరణ: ప్రతిరోజూ రాత్రి 8కు మందు తీసుకోవాలని గుర్తు చేయి","setup.medicines.listen":"మాట్లాడటానికి నొక్కండి","setup.medicines.stop":"ఆపండి","setup.medicines.send":"అర్థం చేసుకోండి",
  "setup.complete.title":"అభినందనలు!","setup.complete.subtitle":"మీ UNK సెటప్ పూర్తయింది.","setup.complete.ready":"మీకు అవసరమైనప్పుడు నేను సిద్ధంగా ఉంటాను.","setup.complete.continue":"UNK కు కొనసాగండి","greeting.morning":"శుభోదయం, {name}. ఈ రోజు మీ దినచర్య ఇదిగో.","greeting.afternoon":"శుభ మధ్యాహ్నం, {name}. ఈ రోజు మీ దినచర్య ఇదిగో.","greeting.evening":"శుభ సాయంత్రం, {name}. ఈ రోజు మీ దినచర్య ఇదిగో.","greeting.item":"{time}కు {label}","greeting.none":"నమస్కారం, {name}. ఈ రోజు ప్రశాంతంగా ఉంది.","setup.greetingFriend":"స్నేహితుడు",
  "directions.title":"దిశలు, స్థలాలు","directions.intro":"ఎక్కడికైనా దారి లేదా దగ్గరి డాక్టర్ల కోసం UNK ను అడగండి. UNK Google Maps తెరుస్తుంది.","directions.askUnk":"దారి కోసం UNK ను అడగండి","directions.doctors":"దగ్గరి డాక్టర్లను కనుగొనండి","ai.bored":"{name}, అర్థమైంది. కాసేపు నడవండి, కుటుంబానికి కాల్ చేయండి, టీ చేసుకోండి, ఇష్టమైన పాట వినండి లేదా పాత ఫొటోలు చూడండి. కుటుంబ కాల్, దినచర్య లేదా షాపింగ్ తెరవాలా?","relationship.caregiver":"సంరక్షకుడు",
  "doctor.title":"UNK డాక్టర్","doctor.intro":"లక్షణాల మార్గదర్శనం, దగ్గరి క్లినిక్‌లు. UNK కారణాలను వివరించి నిజమైన డాక్టర్లను కనుగొంటుంది; మీ డాక్టర్‌కు ప్రత్యామ్నాయం కాదు.","doctor.symptomsTitle":"మీ లక్షణాలు తనిఖీ చేయండి","doctor.describe":"మీకు ఎలా ఉందో చెప్పండి","doctor.symptomPlaceholder":"ఉదాహరణ: రెండు రోజులుగా జ్వరం, దగ్గు, బలహీనత…","doctor.severity":"లక్షణాలు ఎంత తీవ్రంగా ఉన్నాయి?","doctor.analyze":"లక్షణాలు పరిశీలించండి","doctor.analyzing":"పరిశీలిస్తోంది…","doctor.urgency":"అత్యవసర స్థాయి","doctor.urgency.emergency":"తీవ్ర అత్యవసరం","doctor.urgency.urgent":"అత్యవసరం","doctor.urgency.routine":"సాధారణం","doctor.urgency.selfCare":"స్వీయ సంరక్షణ","doctor.chip.fever":"జ్వరం","doctor.chip.headache":"తలనొప్పి","doctor.chip.cough":"దగ్గు","doctor.chip.chestPain":"ఛాతి నొప్పి","doctor.chip.dizziness":"తల తిరగడం","doctor.chip.stomachPain":"కడుపు నొప్పి","doctor.possible":"సంభావ్య సమస్యలు (డాక్టర్ పరిశీలనకు)","doctor.nextSteps":"సూచించిన తదుపరి చర్యలు","doctor.nearbyTitle":"మీ దగ్గరి డాక్టర్లు","doctor.nearbyHint":"నిజమైన క్లినిక్‌లు, ఆసుపత్రులు వెతకడానికి మీ స్థానాన్ని వాడుతుంది. అడిగినప్పుడు అనుమతించండి.","doctor.findNearby":"దగ్గరి డాక్టర్లను కనుగొనండి","doctor.finding":"దగ్గరి డాక్టర్లను వెతుకుతోంది…","doctor.openMaps":"మ్యాప్‌లో తెరవండి","doctor.locationDenied":"స్థాన అనుమతి నిరాకరించబడింది. బ్రౌజర్ సెట్టింగ్‌లలో అనుమతించి మళ్లీ ప్రయత్నించండి.","doctor.locationUnsupported":"ఈ పరికరం స్థానాన్ని ఇవ్వలేదు. Maps తెరిచి డాక్టర్లను వెతకండి.","doctor.noneFound":"దగ్గర క్లినిక్ దొరకలేదు. మళ్లీ ప్రయత్నించండి లేదా Google Mapsలో వెతకండి.","doctor.searchFailed":"ఇప్పుడు వెతకలేకపోయాం. మళ్లీ ప్రయత్నించండి.","doctor.forUser":"{name} కోసం వ్యక్తిగతం",
};
const te: TranslationCatalog = { ...en, ...overrides };
export default te;
